In [1]:
import numpy as np
m= np.arange(4).reshape(1,-1)
n= np.arange(4).reshape(-1,1)

f= np.array([1,2,3,4])
g= np.array([1,1,1,1])
f=np.concatenate((f,np.zeros(3)))
g=np.concatenate((g,np.zeros(3)))

h= (f[m]*g[n-m]).sum(axis=1)
h

array([ 1.,  3.,  6., 10.])

In [2]:
import numpy as np
m= np.arange(3).reshape(1,-1)
n= np.arange(3).reshape(-1,1)

f= np.array([0,1,2])
g= np.array([0,1,2,])
f=np.concatenate((f,np.zeros(2)))
g=np.concatenate((g,np.zeros(2)))

h= (f[m]*g[n-m]).sum(axis=1)
h

array([0., 0., 1.])

In [3]:
import numpy as np
m= np.arange(3).reshape(1,-1)
n= np.arange(3).reshape(-1,1)

f= np.array([0,1,2])
g= np.array([0,1,2,])
f=np.concatenate((f,np.zeros(3)))
g=np.concatenate((g,np.zeros(3)))

h= (f[m]*g[n-m]).sum(axis=1)
h

array([0., 0., 1.])

In [4]:
import numpy as np
m= np.arange(4).reshape(1,-1)
n= np.arange(2).reshape(-1,1)

x= np.array([1,1,1,1])
w= np.array([1,1])
x=np.concatenate((x,np.zeros(3)))
w=np.concatenate((w,np.zeros(1)))

y= (x[m]*w[n-m]).sum(axis=1)
y

array([3., 3.])

In [5]:
import numpy as np
m= np.arange(4).reshape(1,-1)
n= np.arange(2).reshape(-1,1)

x= np.array([1,1,1,1])
w= np.array([1,1])
x=np.concatenate((x,np.zeros(3)))
w=np.concatenate((w,np.zeros(2)))

y= (x[m]*w[n-m]).sum(axis=1)
y

array([2., 2.])

In [6]:
ys = [1, 0, 0, 0,0,0,0,0]
hs = np.dft.dft(ys)
print(hs)

AttributeError: module 'numpy' has no attribute 'dft'

In [7]:
from __future__ import print_function, division

import thinkdsp
import thinkplot

import numpy as np

import warnings
warnings.filterwarnings('ignore')

PI2 = 2 * np.pi

np.set_printoptions(precision=3, suppress=True)
%matplotlib inline

In [8]:
ys = [1, 0, 0, 0,0,0,0,0]
hs = np.dft.dft(ys)
print(hs)

AttributeError: module 'numpy' has no attribute 'dft'

In [ ]:
ys = [1, 0, 0, 0,0,0,0,0]
hs = np.dft.dft(ys)
print(hs)

In [ ]:
ys = [1, 0, 0, 0,0,0,0,0]
hs = np.fft.fft(ys)
print(hs)

In [9]:
def analyze2(ys, freqs, ts):
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    amps = M.conj().transpose().dot(ys) / N
    return amps

In [10]:

N = 8
amps = np.array([1, 0, 0, 0,0,0,0,0])
freqs = np.arange(N)
ts = np.arange(N) / N
ys = synthesize2(amps, freqs, ts)

amps3 = analyze2(ys, freqs, ts)
print(amps3)

NameError: name 'synthesize2' is not defined

In [11]:
%matplotlib inline

import thinkdsp
import thinkplot
import thinkstats2

import numpy as np

PI2 = 2 * np.pi

In [12]:
def analyze2(ys, freqs, ts):
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    amps = M.conj().transpose().dot(ys) / N
    return amps

In [13]:
N = 8
amps = np.array([1, 0, 0, 0,0,0,0,0])
freqs = np.arange(N)
ts = np.arange(N) / N
ys = synthesize2(amps, freqs, ts)

amps3 = analyze2(ys, freqs, ts)
print(amps3)

NameError: name 'synthesize2' is not defined

In [14]:
def synthesize1(amps, freqs, ts):
    components = [thinkdsp.ComplexSinusoid(freq, amp)
                  for amp, freq in zip(amps, freqs)]
    signal = thinkdsp.SumSignal(*components)
    ys = signal.evaluate(ts)
    return ys

In [15]:
def synthesize2(amps, freqs, ts):
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    ys = np.dot(M, amps)
    return ys

In [16]:
def analyze1(ys, freqs, ts):
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    amps = np.linalg.solve(M, ys)
    return amps

In [17]:
N = 8
amps = np.array([1, 0, 0, 0,0,0,0,0])
freqs = np.arange(N)
ts = np.arange(N) / N
ys = synthesize2(amps, freqs, ts)

amps3 = analyze2(ys, freqs, ts)
print(amps3)

[ 1.+0.j -0.+0.j -0.-0.j -0.+0.j  0.-0.j -0.-0.j -0.-0.j  0.+0.j]


In [18]:

def synthesis_matrix(N):
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    return M

In [19]:
def dft(ys):
    N = len(ys)
    M = synthesis_matrix(N)
    amps = M.conj().transpose().dot(ys)
    return amps

In [20]:
print(dft(ys))

[ 8.+0.j -0.+0.j -0.-0.j -0.+0.j  0.-0.j -0.-0.j -0.-0.j  0.+0.j]


In [21]:
N = 8
amps = np.array([1, 1, 1, 1,1,1,1,1])
freqs = np.arange(N)
ts = np.arange(N) / N
ys = synthesize2(amps, freqs, ts)

amps3 = analyze2(ys, freqs, ts)
print(amps3)

[1.+0.j 1.-0.j 1.+0.j 1.+0.j 1.+0.j 1.-0.j 1.-0.j 1.-0.j]


In [22]:
def synthesis_matrix(N):
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    return M

In [23]:
def dft(ys):
    N = len(ys)
    M = synthesis_matrix(N)
    amps = M.conj().transpose().dot(ys)
    return amps

In [24]:
print(dft(ys))

[8.+0.j 8.-0.j 8.+0.j 8.+0.j 8.+0.j 8.-0.j 8.-0.j 8.-0.j]


In [25]:
N = 8
amps = np.array([1, -1, 1, -1,1,-1,1,-1])
freqs = np.arange(N)
ts = np.arange(N) / N
ys = synthesize2(amps, freqs, ts)

amps3 = analyze2(ys, freqs, ts)
print(amps3)

[ 1.+0.j -1.-0.j  1.-0.j -1.-0.j  1.-0.j -1.+0.j  1.+0.j -1.+0.j]


In [26]:
def synthesis_matrix(N):
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    return M

In [27]:
def dft(ys):
    N = len(ys)
    M = synthesis_matrix(N)
    amps = M.conj().transpose().dot(ys)
    return amps

In [28]:
print(dft(ys))

[ 8.+0.j -8.-0.j  8.-0.j -8.-0.j  8.-0.j -8.+0.j  8.+0.j -8.+0.j]


In [29]:
N = 8
amps = np.array([3, 0, 2, 0,2,0,2,0])
freqs = np.arange(N)
ts = np.arange(N) / N
ys = synthesize2(amps, freqs, ts)

amps3 = analyze2(ys, freqs, ts)
print(amps3)

[ 3.+0.j -0.-0.j  2.+0.j -0.-0.j  2.-0.j -0.+0.j  2.-0.j  0.+0.j]


In [30]:
def synthesis_matrix(N):
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    return M

In [31]:
def dft(ys):
    N = len(ys)
    M = synthesis_matrix(N)
    amps = M.conj().transpose().dot(ys)
    return amps

In [32]:
print(dft(ys))

[24.+0.j -0.-0.j 16.+0.j -0.-0.j 16.-0.j -0.+0.j 16.-0.j  0.+0.j]
